apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rosa-regional-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cdoan1/rosa-regional-platform-api
    targetRevision: define-application-deployment
    path: deployment/helm/rosa-regional-platform
    helm:
      parameters:
        - name: app.args.maestroUrl
          value: http://maestro-http.maestro:8080
        - name: app.args.logLevel
          value: info
  destination:
    server: https://kubernetes.default.svc
    namespace: rosa-regional-platform
  ignoreDifferences:
    - group: eks.amazonaws.com
      kind: TargetGroupBinding
      jsonPointers:
        - /spec/targetGroupARN
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
